version: '3.8'

services:
  lightrag:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lightrag
    depends_on:
      - neo4j
    ports:
      - "8000:8000"
    env_file: 
      - .env  # Loads environment variables from the .env file
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=your_password
    volumes:
      - ./app:/app/local_neo4jWorkDir

  neo4j:
    image: neo4j:5.24.2
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/your_password
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
